parameters:
    open_orchestra_bbcode.validators :
        url : JBBCode\validators\UrlValidator
        css_color : JBBCode\validators\CssColorValidator

    open_orchestra_bbcode.code_definitions :
        title :
            tag : h
            html : <h{option}>{param}</h{option}>
            parameters :
                use_option : true

        bold :
            tag : b
            html : <strong>{param}</strong>
        italic :
            tag : i
            html : <em>{param}</em>
        underline :
            tag : u
            html : <u>{param}</u>

        color :
            tag : color
            html : <span style="color: {option}">{param}</span>
            parameters :
                use_option : true
                option_validator : css_color

        paragraph :
            tag : p
            html : <p>{param}</p>

        unorganized_list :
            tag : ul
            html : <ul>{param}</ul>

        organized_list :
            tag : ol
            html : <ol>{param}</ol>

        list_item :
            tag : li
            html : <li>{param}</li>

        url :
            tag : url
            html : <a href="{param}">{param}</a>
            parameters :
                parse_content : false
                body_validator : url
        url_labelled :
            tag : url
            html : <a href="{option}">{param}</a>
            parameters :
                use_option : true
                parse_content : true
                option_validator : url

        img :
            tag : img
            html : <img src="{param}" />
            parameters :
                use_option : false
                parse_content : false
                body_validator : url
        img_with_alt :
            tag : img
            html : <img src="{param}" alt="{option}" />
            parameters :
                use_option : true
                parse_content : false
                body_validator : url
